### ISSUE TITLE
Cannot install new npm packages

### ISSUE THREAD

**Issue by exog3n** [mhueter/docker-node-express-boilerplate#4]
Unfortunately there is an issue with the extend of the current images. I realized that i cannot install new npm packages (i can but then a MODULE_NOT_FOUND appears). Do you have a any workaround for this? i think the solution is on docker-compose.yml and Dockerfile. Maybe the place of the node_modules folder...

**Comment by nsyed1** [comment]
Don't know the fix but a work around :
Try commenting out the line containing the path to node_modules in your docker compose file, under services: app: volumes:

**Comment by hueter** [comment]
hi @exog3n thanks for bringing this to my attention. I believe I had made a mistake on the line pointed out by @nsyed1 , but I changed it in this commit https://github.com/hueter/docker-node-express-boilerplate/commit/3bdc82ed3f788a8e6afc1bb28f4f24910f65b637 and it works for me locally. If you add this change I think you should be able to `npm install` new packages even while the server is running.

Let me know if it works for you! Thanks
